### PR TITLE
Bump Rubocop

### LINKED ISSUE #55: Build is broken
Hey all! Stopping by to look at this and I happened to notice the Travis build is failing for what appears to be some time. Was going to try to submit a PR to fix but I can't see the output. Wanted to drop a line to at least make you aware.

Thanks for creating the library!

### PR DESCRIPTION
**Pull request by jekyllbot**
Fix #55 

- [x] Use latest Rubocop
- [x] Drop support for Ruby < 2.3

### CODE REVIEW

**Comment by DirtyF** [comment]
As this implicitly drops support for Ruby < 2.3, we'll have to include this in  a 0.4.0 release.

**Comment by ashmaroli** [comment]
You should either drop support for EOL  Rubies *explicitly* via the `gemspec` or avoid using Ruby 2.3 syntax by autocorrecting with Rubocop 0.57.x instead..

**Comment by pathawks** [comment]
Let’s drop support explicitly, so if anybody _does_ need to keep using older Rubys they can keep using the old version 👍🏼

**Comment by ashmaroli** [comment]
> Let’s drop support explicitly

At the Jekyll front, all is well since `jekyll-3.8.4` is already locked to `mercenary-0.3.x`..

**Comment by DirtyF** [comment]
@jekyllbot: :shipit: +dev

**Pull request merged**
